framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        allowed_locales: ['en', 'cz', 'de', 'nl', 'pl', 'ru', 'sk', 'tr', 'ua']
        fallbacks: ['en']
