## Overview
# This Docker Compose configuration defines two services: web and db.
# The web service sets up a PHP environment with Apache, while the db service sets up a MySQL database.

version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    # database connection config
    environment:
      - DATABASE_DRIVER=pdo_mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=becvar_site
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    volumes:
      - ./docker/configs/php.ini:/usr/local/etc/php/php.ini:ro

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=becvar_site
