## Overview
# This Docker Compose configuration defines local development services.
version: '3'

# docker network config
networks:
    becvar_site:
        driver: bridge

services:
    # database container
    mysql:
        image: mysql:latest
        container_name: becvar_site_mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./docker/configs/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
            - ./docker/services/mysql_database:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - becvar_site

    # web server container
    apache_php:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: becvar_site_apache
        restart: always
        depends_on:
            - mysql
        environment:
            - DATABASE_DRIVER=pdo_mysql
            - DATABASE_HOST=mysql
            - DATABASE_PORT=3306
        volumes:
            - ./docker/configs/apache-site.conf:/etc/apache2/sites-available/000-default.conf
            - ./docker/configs/php.ini:/usr/local/etc/php/php.ini:ro
            - ./:/var/www
        ports:
            - "80:80"
        networks:
            - becvar_site
