# this file is the entry point to configure your own services.
# files in the packages/ subdirectory configure your dependencies.

# put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # automatically injects dependencies in your services.
        autoconfigure: true # automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

    # twig extension (link detect & replace with |linkify)
    App\Twig\LinkifyExtension:
        tags:
            - { name: 'twig.extension' }

    # --------------------------------------------------------------------------------- #
    # error event subscriber
    App\Event\Subscriber\ErrorEventSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # check user auth for admin sites
    App\Middleware\AuthentificatedCheckMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 9 }

    # translations set checker
    App\Middleware\TranslationsMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 8 }

    # resources build checker
    App\Middleware\AssetsCheckMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 7 }

    # maintenance mode checker
    App\Middleware\MaintenanceMiddleware:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 6 }

    # visitor system service
    App\Middleware\VisitorSystemMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 5 }

    # auto login service
    App\Middleware\AutoLoginMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 4 }

    # security check service
    App\Middleware\SecurityCheckMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 3 }

    # database online checker
    App\Middleware\DatabaseOnlineMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 2 }

    # escape request data
    App\Middleware\EscapeRequestDataMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 1 }
    # --------------------------------------------------------------------------------- #
