# App deploy action
name: Deploy

on:
  release: # trigger the workflow when a new release is created
    types: [created]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # deploy to the server using SSH
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22

        # script to run on the server
        script: |
          cd /services/website/becvar.xyz
          sudo systemctl stop apache2
          sh scripts/clear.sh
          git pull
          sed -i 's/^\(APP_ENV=\)dev/\1prod/' .env
          sh scripts/install.sh
          php bin/console doctrine:migrations:migrate --no-interaction --env=prod
          sudo systemctl start apache2
