name: Deploy

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

      # This step performs the deployment of the application to the server using SSH
      # It utilizes the appleboy/ssh-action, which allows connecting to the server and executing a script
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo systemctl stop apache2

          if [ ! -d "/services/website/becvar.xyz" ]; then
            git clone git@github.com:lordbecvold/becvar-site.git /services/website/becvar.xyz
          fi

          cd /services/website/becvar.xyz/
          git update-index --skip-worktree .env .env.prod .env.dev .env.test

          sh scripts/clear.sh
          sh scripts/install.sh

          sh scripts/create-database.sh
          sh scripts/migrate.sh

          sudo systemctl start apache2
