# deploy app to the production server
name: Deploy

on:
  release:
    types: [created]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # deploy to the server using SSH
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22

        # script to run on the server
        script: |
          # stop web server
          sudo systemctl stop apache2

          # go to the project directory
          cd /services/website/becvar-site

          # clear requirements & cache
          sudo sh scripts/clear.sh

          # pull the latest changes
          git pull

          # set the environment to production
          sed -i 's/^\(APP_ENV=\)dev/\1prod/' .env

          # install dependencies with composer
          composer install --no-interaction --no-progress --no-suggest

          # install npm dependencies
          npm install --loglevel=error

          # build assets
          npm run build

          # migrate database
          php bin/console doctrine:database:create --if-not-exists
          php bin/console doctrine:migrations:migrate --no-interaction

          # update projects database
          php bin/console projects:list:update

          # fix storage permissions
          sudo chmod -R 777 var/
          sudo chown -R www-data:www-data var/

          # start web server
          sudo systemctl start apache2
