name: Deploy

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to server
        env:
          SERVER_SSH: ${{ secrets.SERVER_SSH }}
        run: |
          ssh -i $SERVER_SSH lordbecvold@89.168.77.11 "bash /services/test.sh"
