# run static code analysis with PHP CodeSniffer
name: PHP-CodeSniffer

on:
  push:
    branches:
      - main

jobs:
  phpcs:
    name: PHP CodeSniffer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # setup PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: intl, pdo_mysql, gd

    # install dependencies
    - name: Install dependencies
      run: composer install --no-interaction --no-progress --no-suggest

    # check code with code sniffer
    - name: Run PHP CodeSniffer
      run: vendor/bin/phpcs
