# run static analysis with PHPStan
name: PHPStan

on:
  push:
    branches:
      - main

jobs:
  phpstan:
    name: PHPStan analyse
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # setup PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: intl, pdo_mysql, gd

    # install dependencies
    - name: Install dependencies
      run: composer install

    # run PHPStan analysis
    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse --configuration phpstan.neon
