# static code analyse with phpstan
name: PHPStan

on:
  push:
    branches:
      - main
      - dev

jobs:
  phpstan:
    name: PHPStan analyse
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # setup php interpreter
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: intl, pdo_mysql, gd

    # composer install
    - name: Install backend dependencies
      run: composer install

    # phpstan process
    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse --configuration phpstan.neon
