name: PHPUnit

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DATABASE_NAME }}
          MYSQL_USER: ${{ env.DATABASE_USERNAME }}
          MYSQL_PASSWORD: ${{ env.DATABASE_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: composer install

      - name: Create and migrate database
        env:
          DB_HOST: ${{ env.DATABASE_HOST }}
          DB_PORT: ${{ env.DATABASE_PORT }}
          DB_DATABASE: ${{ env.DATABASE_NAME }}
          DB_USERNAME: ${{ env.DATABASE_USERNAME }}
          DB_PASSWORD: ${{ env.DATABASE_PASSWORD }}
        run: php bin/console doctrine:database:create --env=dev && php bin/console doctrine:migrations:migrate --env=dev --no-interaction

      - name: Run PHPUnit tests
        env:
          DB_HOST: ${{ env.DATABASE_HOST }}
          DB_PORT: ${{ env.DATABASE_PORT }}
          DB_DATABASE: ${{ env.DATABASE_NAME }}
          DB_USERNAME: ${{ env.DATABASE_USERNAME }}
          DB_PASSWORD: ${{ env.DATABASE_PASSWORD }}
        run: vendor/bin/phpunit
