name: PHP PHPUnit Tests

on:
  push:
    branches:
      - main

jobs:
  phpunit:
    name: Run PHPUnit
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, pdo_mysql, pdo, mysqli, zip

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --no-interaction --prefer-dist

      - name: Prepare PHPUnit config

      - name: Create database and run migrations
        run: |
          php bin/console doctrine:database:create --if-not-exists
          php bin/console doctrine:migrations:migrate --no-interaction --all-or-nothing

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
